- hosts: all
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true

- hosts: all
  roles:
    - undergreen.mongodb
  vars:
    mongodb_net_http_enabled: true
    mongodb_net_bindip: 0.0.0.0
    mongodb_pymongo_pip_version: 4.1.1
    mongodb_security_authorization: "enabled"
    mongodb_users:
      - {
          name: "{{ mongodb_user }}",
          password: "{{ mongodb_pass }}",
          roles: readWrite,
          database: "{{ mongodb_db }}"
        }
