version: "3.9"
    
services:
  frontend:
    build: 
      context: artifacts
      dockerfile: ../docker/Dockerfile_frontend
    restart: always
    depends_on:
      - assets
      - contacts
      - tickets0
    environment:
      BACKEND: "http://tickets0:8999"
      CONTACTS: "http://contacts:9001"
      ASSETS: "http://assets:9000"
    ports:
      - "8888:8888"

  assets:
    build: 
      context: artifacts
      dockerfile: ../docker/Dockerfile_assets
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    restart: always
    environment:
      PORT: 9000
      MONGODB_PASS: tickets
      MONGODB_USER: tickets
      MONGODB_CONN_STRING: "mongodb://mongodb:27017/tickets"

  contacts:
    build: 
      context: artifacts
      dockerfile: ../docker/Dockerfile_contacts
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
    restart: always
    environment:
      PORT: 9001
      MONGODB_PASS: tickets
      MONGODB_USER: tickets
      MONGODB_CONN_STRING: "mongodb://mongodb:27017/tickets"

  tickets0:
    build: 
      context: artifacts
      dockerfile: ../docker/Dockerfile_tickets
    ports:
      - "8999:8999"
    depends_on:
      - mongodb
    restart: always
    environment:
      PORT: 8999
      MONGODB_PASS: tickets
      MONGODB_USER: tickets
      MONGODB_CONN_STRING: "mongodb://mongodb:27017/tickets"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - type: volume
        source: mongodata
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_USERNAME: tickets
      MONGO_INITDB_PASSWORD: tickets
      MONGO_INITDB_DATABASE: tickets

volumes:
  mongodata:
