---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-frontend
  labels:
    app: ticketing-frontend
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: ticketing-frontend
  template:
    metadata:
      labels:
        app: ticketing-frontend
    spec:
      containers:
      - name: ticketing-frontend
        image: ipcrm/ticketing-frontend
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: BACKEND
          value: "{{ .datalayer_backend }}"
        ports:
        - containerPort: 8080
          name: ticketing-fe
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-frontend
  labels:
    apps: ticketing-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ticketing-frontend
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ticketing-frontend
  loadBalancerSourceRanges: [ {{range  $i, $e := .cidr_block }}{{if ne . ""}}{{if $i}},{{end}}{{$e}}/32{{end}}{{end}} ]
