---
sharedeks:
  steps:
    - name: sharedeks
      extension: EKS
      args:
        region: us-east-2
        deployment_name: sharedeks
    - name: lacework
      extension: Kubectl
      tags: monitoring
      source:
        location: "https://raw.githubusercontent.com/lacework-dev/detc-resources/${GIT_BRANCH:-main}/apps/lacework/kube-manifest/lacework-all-k8s.yaml"
        templates:
          - "lacework-all-k8s.yaml"
      needs:
        - sharedeks
      helpers:
        - helper: WriteValue
          run_on_dryrun: true
          args:
            name: kubectl_config
            dstfile: kubectl
      lookup:
        control_plane_url: /sharedeks/outputs/cluster_endpoint
        kubectl_config: /sharedeks/outputs/kubectl_config
      args:
        lw_access_token: !secret lacework.access_token
        kubectl_config_file: kubectl
        kube_manifest_path: "lacework-all-k8s.yaml"
