sharedgke:
  steps:
    - name: sharedgke
      extension: GKE
      tags: infrastructure
      args:
        region: !secret gcp.region
        project: !secret gcp.project_id
        cluster_name: "sharedgke-k8-cluster"
    - name: lacework
      extension: Kubectl
      description: This step deploys Lacework instrumentation to an existing K8s cluster
      tags: monitoring
      source:
        location: "https://raw.githubusercontent.com/lacework-dev/detc-resources/${GIT_BRANCH:-main}/apps/lacework/kube-manifest/lacework-all-k8s.yaml"
        templates:
          - "lacework-all-k8s.yaml"
      needs:
        - sharedgke
      helpers:
        - helper: GKEKubectl
      lookup:
        control_plane_url: /sharedgke/outputs/cluster_endpoint
        kubectl_config: /sharedgke/outputs/kubectl_config
      args:
        cluster_name: !lookup /sharedgke/sharedgke/outputs/cluster_name
        lw_access_token: !secret lacework.access_token
        kubectl_config_file: kubectl
        kube_manifest_path: "lacework-all-k8s.yaml"
